# repl dev environment

import os

os.environ["DISPLAY"] = ":0"

from webdriver import ManagerWebdriver

from sofascrape.conf.config import load_config
from sofascrape.db.manager import DatabaseManager
from sofascrape.football.lineupComonent import FootballLineupComponentScraper

# 1. Load our new infrastructure
config = load_config()
db = DatabaseManager(config)

# 2. Spin up your custom proxy-rotating webdriver
print("Spawning Webdriver...")
mw = ManagerWebdriver()
driver = mw.spawn_webdriver()

# 3. Let's try to scrape the Scottish Premiership (Assuming ID is 36, change if needed!)
# Actually, let's use Tournament ID 17 (Premier League) or whatever you know works.
match_id = 14035506

scraper = FootballLineupComponentScraper(matchid=match_id, webdriver=driver, cfg=config)

# 4. Execute the scrape steps
scraper.get_data()
print("Raw Data Fetched!")

scraper.parse_data()

# Let's look at what we got:
print(f"\n--- Result ---")
print(scraper.data.model_dump_json(indent=6))  # Pretty print the JSON

# 5. Let's test saving it to our brand new Postgres table!
# TODO: create this functions
    db.upsert_(
    )

# Always clean up the browser!
print("Closing webdriver...")
driver.close()



'''
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
print(scraper.data.model_dump_json(indent=6))  # Pretty print the JSON
--- Result ---                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      "confirmed": true,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
      "home": {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
            "players": [                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                  {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                        "player": {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                              "name": "Darren Jamieson",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                              "id": 164359,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                              "firstName": "",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                              "lastName": "",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                              "slug": "jamieson-darren",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                              "shortName": "D. Jamieson",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                              "position": "G",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                              "jerseyNumber": "1",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                              "height": 185,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                              "userCount": 2,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                              "sofascoreId": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                              "country": {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                    "name": "Scotland",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                    "slug": "scotland",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                    "alpha2": "SX",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                    "alpha3": "SCO"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                              },                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                              "marketValueCurrency": "EUR",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                              "dateOfBirthTimestamp": 666576000,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                              "proposedMarketValueRaw": {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                    "value": 165000,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                    "currency": "EUR"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                              }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                        },                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                        "teamId": 2370,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                        "shirtNumber": 1,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                        "jerseyNumber": "1",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                        "position": "G",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        "substitute": false,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                        "captain": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        "statistics": {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                              "totalPass": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                              "accuratePass": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                              "totalLongBalls": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                              "accurateLongBalls": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                              "goalAssist": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                              "totalCross": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                              "accurateCross": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                              "aerialLost": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                              "aerialWon": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                              "duelLost": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                              "duelWon": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                              "challengeLost": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                              "totalContest": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                              "wonContest": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                              "dispossessed": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                              "totalClearance": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                              "outfielderBlock": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                              "interceptionWon": null,                                                                                                        
                              "totalTackle": null,                                                                                                            
                              "wasFouled": null,                                                                                                              
                              "fouls": null,                                                                                                                  
                              "totalOffside": null,                                                                                                           
                              "minutesPlayed": 90,                                                                                                            
                              "touches": null,                                                                                                                
                              "rating": null,                                                                                                                 
                              "possessionLostCtrl": null,                                                                                                     
                              "expectedGoals": null,                                                                                                          
                              "expectedAssists": null,                                                                                                        
                              "keyPass": null,                                                                                                                
                              "ratingVersions": null,                                                                                                         
                              "goodHighClaim": null,                                                                                                          
                              "savedShotsFromInsideTheBox": null,                                                                                             
                              "saves": null,                                                                                                                  
                              "totalKeeperSweeper": null,                                                                                                     
                              "accurateKeeperSweeper": null,                                                                                                  
                              "goalsPrevented": null,                                                                                                         
                              "errorLeadToAShot": null,                                                                                                       
                              "punches": null,                                                                                                                
                              "bigChanceCreated": null,                                                                                                       
                              "bigChanceMissed": null,                                                                                                        
                              "shotOffTarget": null,                                                                                                          
                              "onTargetScoringAttempt": null,                                                                                                 
                              "blockedScoringAttempt": null,                                                                                                  
                              "goals": 0                                                                                                                      
                        }                                                                                                                                     
                  },  


                  ... more home players 


       "away": {                                                                                                                                                                                                                                                                                                                                                                             
                "players": [                                                                                                                                                                                                                                                                                                                                                                    
                      {                                                                                                                                                                                                                                                                                                                                                                         
                            "player": {                                                                                                                                                                                                                                                                                                                                                         
                                  "name": "Robbie Mutch",                                                                                                                                                                                                                                                                                                                                       
                                  "id": 911431,                                                                                                                                                                                                                                                                                                                                                 
                                  "firstName": null,                                                                                                                                                                                                                                                                                                                                            
                                  "lastName": null,                                                                                                                                                                                                                                                                                                                                             
                                  "slug": "mutch-robbie",                                                                                                                                                                                                                                                                                                                                       
                                  "shortName": "R. Mutch",                                                                                                                                                                                                                                                                                                                                      
                                  "position": "G",                                                                                                                                                                                                                                                                                                                                              
                                  "jerseyNumber": "1",                                                                                                                                                                                                                                                                                                                                          
                                  "height": 194,                                                                                                                                                                                                                                                                                                                                                
                                  "userCount": 3,                                                                                                                                                                                                                                                                                                                                               
                                  "sofascoreId": null,                                                                                                                                                                                                                                                                                                                                          
                                  "country": {                                                                                                                                                                                                                                                                                                                                                  
                                        "name": "Scotland",                                                                                                                                                                                                                                                                                                                                     
                                        "slug": "scotland",                                                                                                                                                                                                                                                                                                                                     
                                        "alpha2": "SX",                                                                                                                                                                                                                                                                                                                                         
                                        "alpha3": "SCO"                                                                                                                                                                                                                                                                                                                                         
                                  },                                                                                                                                                                                                                                                                                                                                                            
                                  "marketValueCurrency": "EUR",                                                                                                                                                                                                                                                                                                                                 
                                  "dateOfBirthTimestamp": 903571200,                                                                                                                                                                                                                                                                                                                            
                                  "proposedMarketValueRaw": {                                                                                                                                                                                                                                                                                                                                   
                                        "value": 26000,                                                                                                                                                                                                                                                                                                                                         
                                        "currency": "EUR"                                                                                                                                                                                                                                                                                                                                       
                                  }                                                                                                                                                                                                                                                                                                                                                             
                            },                                                                                                                                                                                                                                                                                                                                                                  
                            "teamId": 8062,                                                                                                                                                                                                                                                                                                                                                     
                            "shirtNumber": 1,                                                                                                                                                                                                                                                                                                                                                   
                            "jerseyNumber": "1",                                                                                                                                                                                                                                                                                                                                                
                            "position": "G",                                                                                                                                                                                                                                                                                                                                                    
                            "substitute": false,                                                                                                                                                                                                                                                                                                                                                
                            "captain": null,                                                                                                                                                                                                                                                                                                                                                    
                            "statistics": {                                                                                                                                                                                                                                                                                                                                                     
                                  "totalPass": null,                                                                                                                                                                                                                                                                                                                                            
                                  "accuratePass": null,                                                                                                                                                                                                                                                                                                                                         
                                  "totalLongBalls": null,                                                                                                                                                                                                                                                                                                                                       
                                  "accurateLongBalls": null,                                                                                                                                                                                                                                                                                                                                    
                                  "goalAssist": null,                                                                                                                                                                                                                                                                                                                                           
                                  "totalCross": null,                                                                                                                                                                                                                                                                                                                                           
                                  "accurateCross": null,                                                                                                                                                                                                                                                                                                                                        
                                  "aerialLost": null,                                                                                                                                                                                                                                                                                                                                           
                                  "aerialWon": null,                                                                                                                                                                                                                                                                                                                                            
                                  "duelLost": null,                                                                                                                                                                                                                                                                                                                                             
                                  "duelWon": null,                                                                                                                                                                                                                                                                                                                                              
                                  "challengeLost": null,                                                                                                                                                                                                                                                                                                                                        
                                  "totalContest": null,                                                                                                                                                                                                                                                                                                                                         
                                  "wonContest": null,                                                                                                                                                                                                                                                                                                                                           
                                  "dispossessed": null,                                                                                                                                                                                                                                                                                                                                         
                                  "totalClearance": null,                                                                                                                                                                                                                                                                                                                                       
                                  "outfielderBlock": null,                                                                                                                                                                                                                                                                                                                                      
                                  "interceptionWon": null,                                                                                                                                                                                                                                                                                                                                      
                                  "totalTackle": null,                                                                                                                                                                                                                                                                                                                                          
                                  "wasFouled": null,                                                                                                                                                                                                                                                                                                                                            
                                  "fouls": null,                                                                                                                                                                                                                                                                                                                                                
                                  "totalOffside": null,                                                                                                                                                                                                                                                                                                                                         
                                  "minutesPlayed": 90,                                                                                                                                                                                                                                                                                                                                          
                                  "touches": null,                                                                                                                                                                                                                                                                                                                                              
                                  "rating": null,                                                                                                                                                                                                                                                                                                                                               
                                  "possessionLostCtrl": null,                                                                                                                                                                                                                                                                                                                                   
                                  "expectedGoals": null,                                                                                                                                                                                                                                                                                                                                        
                                  "expectedAssists": null,                                                                                                                                                                                                                                                                                                                                      
                                  "keyPass": null,                                                                                                                                                                                                                                                                                                                                              
                                  "ratingVersions": null,                                                                                                                                                                                                                                                                                                                                       
                                  "goodHighClaim": null,                                                                                                                                                                                                                                                                                                                                        
                                  "savedShotsFromInsideTheBox": null,                                                                                                                                                                                                                                                                                                                           
                                  "saves": null,                                                                                                                                                                                                                                                                                                                                                
                                  "totalKeeperSweeper": null,                                                                                                                                                                                                                                                                                                                                   
                                  "accurateKeeperSweeper": null,                                                                                                                                                                                                                                                                                                                                
                                  "goalsPrevented": null,                                                                                                                                                                                                                                                                                                                                       
                                  "errorLeadToAShot": null,                                                                                                                                                                                                                                                                                                                                     
                                  "punches": null,                                                                                                                                                                                                                                                                                                                                              
                                  "bigChanceCreated": null,                                                                                                                                                                                                                                                                                                                                     
                                  "bigChanceMissed": null,                                                                                                                                                                                                                                                                                                                                      
                                  "shotOffTarget": null,                                                                                                                                                                                                                                                                                                                                        
                                  "onTargetScoringAttempt": null,                                                                                                                                                                                                                                                                                                                               
                                  "blockedScoringAttempt": null,                                                                                                                                                                                                                                                                                                                                
                                  "goals": 0                                                                                                                                                                                                                                                                                                                                                    
                            }                                                                                                                                                                                                                                                                                                                                                                   
                      },


'''
