# repl dev environment

import os

os.environ["DISPLAY"] = ":0"

from webdriver import ManagerWebdriver

from sofascrape.conf.config import load_config
from sofascrape.db.manager import DatabaseManager
from sofascrape.football.incidentsComponent import FootballIncidentsComponentScraper

# 1. Load our new infrastructure
config = load_config()
db = DatabaseManager(config)

# 2. Spin up your custom proxy-rotating webdriver
print("Spawning Webdriver...")
mw = ManagerWebdriver()
driver = mw.spawn_webdriver()

# 3. Let's try to scrape the Scottish Premiership (Assuming ID is 36, change if needed!)
# Actually, let's use Tournament ID 17 (Premier League) or whatever you know works.
match_id = 14035506

scraper = FootballIncidentsComponentScraper(
    matchid=match_id, webdriver=driver, cfg=config
)

# 4. Execute the scrape steps
scraper.get_data()
print("Raw Data Fetched!")

scraper.parse_data()

# Let's look at what we got:
print(f"\n--- Result ---")
print(scraper.data.model_dump_json(indent=6))  # Pretty print the JSON

print(scraper.data.incidents[12].model_dump_json(indent=2))  # Pretty print the JSON

# 5. Let's test saving it to our brand new Postgres table!
# TODO:
db.upsert_match_incident(match_id=match_id, parsed_incidents=scraper.data)
# Always clean up the browser!
print("Closing webdriver...")
driver.close()


""" 
{                                                                                                                                                                                                                                                                              
  "incidentType": "card",                                                                                                                                                                                                                                                      
  "player": {                                                                                                                                                                                                                                                                  
    "name": "David Eguaibor",                                                                                                                                                                                                                                                  
    "id": 1391648,                                                                                                                                                                                                                                                             
    "firstName": "David",                                                                                                                                                                                                                                                      
    "lastName": "Eguaibor",                                                                                                                                                                                                                                                    
    "slug": "david-eguaibor",                                                                                                                                                                                                                                                  
    "shortName": "D. Eguaibor",                                                                                                                                                                                                                                                
    "position": "F",                                                                                                                                                                                                                                                           
    "jerseyNumber": "20",                                                                                                                                                                                                                                                      
    "height": 189,                                                                                                                                                                                                                                                             
    "userCount": 7,                                                                                                                                                                                                                                                            
    "sofascoreId": null,                                                                                                                                                                                                                                                       
    "country": null,                                                                                                                                                                                                                                                           
    "marketValueCurrency": "EUR",
    "dateOfBirthTimestamp": 1073433600,
    "proposedMarketValueRaw": null
  },
  "playerName": null,
  "reason": null,
  "rescinded": false,
  "id": 123713261,
  "time": 88,
  "isHome": false,
  "incidentClass": "yellow",
  "reversedPeriodTime": 3
}

{
  "incidentType": "substitution",
  "playerIn": {
    "name": "Nicky Jamieson",
    "id": 988709,
    "firstName": "",
    "lastName": "",
    "slug": "nicky-jamieson",
    "shortName": "N. Jamieson",
    "position": "D",
    "jerseyNumber": "5",
    "height": 193,
    "userCount": 6,
    "sofascoreId": null,
    "country": null,
    "marketValueCurrency": "EUR",
    "dateOfBirthTimestamp": 839030400,
    "proposedMarketValueRaw": {
      "value": 110000,
      "currency": "EUR"
    }
  },
  "playerOut": {
    "name": "Ross Taylor",
    "id": 1389788,
    "firstName": null,
    "lastName": null,
    "slug": "ross-taylor",
    "shortName": "R. Taylor",
    "position": null,
    "jerseyNumber": "11",
    "height": null,
    "userCount": 3,
    "sofascoreId": null,
    "country": null,
    "marketValueCurrency": "EUR",
    "dateOfBirthTimestamp": 1072915200,
    "proposedMarketValueRaw": null
  },
  "id": 124260146,
  "time": 87,
  "addedTime": null,
  "injury": false,
  "isHome": true,
  "incidentClass": "regular",
  "reversedPeriodTime": 4
}
{
  "incidentType": "period",
  "text": "HT",
  "homeScore": 1,
  "awayScore": 0,
  "isLive": false,
  "time": 45,
  "addedTime": 999,
  "timeSeconds": 2700,
  "reversedPeriodTime": 1,
  "reversedPeriodTimeSeconds": 0,
  "periodTimeSeconds": 2700
}
{
  "incidentType": "goal",
  "homeScore": 1,
  "awayScore": 0,
  "player": {
    "name": "Dale Carrick",
    "id": 250215,
    "firstName": null,
    "lastName": null,
    "slug": "dale-carrick",
    "shortName": "D. Carrick",
    "position": "F",
    "jerseyNumber": "15",
    "height": 180,
    "userCount": 5,
    "sofascoreId": null,
    "country": null,
    "marketValueCurrency": "EUR",
    "dateOfBirthTimestamp": 757900800,
    "proposedMarketValueRaw": {
      "value": 160000,
      "currency": "EUR"
    }
  },
  "assist1": {
    "name": "Ross Taylor",
    "id": 1389788,
    "firstName": null,
    "lastName": null,
    "slug": "ross-taylor",
    "shortName": "R. Taylor",
    "position": null,
    "jerseyNumber": "11",
    "height": null,
    "userCount": 3,
    "sofascoreId": null,
    "country": null,
    "marketValueCurrency": "EUR",
    "dateOfBirthTimestamp": 1072915200,
    "proposedMarketValueRaw": null
  },
  "assist2": null,
  "footballPassingNetworkAction": null,
  "id": 320389636,
  "time": 6,
  "isHome": true,
  "incidentClass": "regular",
  "reversedPeriodTime": 40
}




# ------


{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
      "incidents": [                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
            {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                  "incidentType": "period",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                  "text": "FT",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                  "homeScore": 1,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                  "awayScore": 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                  "isLive": false,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                  "time": 90,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                  "addedTime": 999,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                  "timeSeconds": 5400,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                  "reversedPeriodTime": 1,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                  "reversedPeriodTimeSeconds": 0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                  "periodTimeSeconds": 2700                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
            },                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
            {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                  "incidentType": "card",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                  "player": {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                        "name": "David Eguaibor",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                        "id": 1391648,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                        "firstName": "David",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                        "lastName": "Eguaibor",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                        "slug": "david-eguaibor",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                        "shortName": "D. Eguaibor",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                        "position": "F",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        "jerseyNumber": "20",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                        "height": 189,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                        "userCount": 7,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                        "sofascoreId": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                        "country": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        "marketValueCurrency": "EUR",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                        "dateOfBirthTimestamp": 1073433600,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                        "proposedMarketValueRaw": null                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                  },                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                  "playerName": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                  "reason": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                  "rescinded": false,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                  "id": 123713261,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                  "time": 88,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                  "isHome": false,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                  "incidentClass": "yellow",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                  "reversedPeriodTime": 3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
            },                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
            {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                  "incidentType": "substitution",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                  "playerIn": {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                        "name": "Nicky Jamieson",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                        "id": 988709,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                        "firstName": "",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        "lastName": "",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                        "slug": "nicky-jamieson",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                        "shortName": "N. Jamieson",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                        "position": "D",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        "jerseyNumber": "5",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                        "height": 193,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                        "userCount": 6,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                        "sofascoreId": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                        "country": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        "marketValueCurrency": "EUR",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                        "dateOfBirthTimestamp": 839030400,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                        "proposedMarketValueRaw": {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                              "value": 110000,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                              "currency": "EUR"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                  },                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                  "playerOut": {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                        "name": "Ross Taylor",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                        "id": 1389788,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                        "firstName": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                        "lastName": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                        "slug": "ross-taylor",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                        "shortName": "R. Taylor",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                        "position": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                        "jerseyNumber": "11",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                        "height": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                        "userCount": 3,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                        "sofascoreId": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                        "country": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        "marketValueCurrency": "EUR",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                        "dateOfBirthTimestamp": 1072915200,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                        "proposedMarketValueRaw": null                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                  },                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                  "id": 124260146,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                  "time": 87,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                  "addedTime": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                  "injury": false,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                  "isHome": true,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                  "incidentClass": "regular",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                  "reversedPeriodTime": 4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
            },                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
            {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                  "incidentType": "substitution",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                  "playerIn": {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                        "name": "Justin Eguaibor",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                        "id": 1184272,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                        "firstName": "Justin Eguaibor",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                        "lastName": "",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                        "slug": "justin-eguaibor",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                        "shortName": "J. Eguaibor",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                        "position": "D",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        "jerseyNumber": "6",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                        "height": 193,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                        "userCount": 6,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                        "sofascoreId": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                        "country": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                        "marketValueCurrency": "EUR",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                        "dateOfBirthTimestamp": 1026691200,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                        "proposedMarketValueRaw": null                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                  },                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                  "playerOut": {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                        "name": "Mackenzie Strachan",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                        "id": 1142352,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                        "firstName": null,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                        "lastName": null,                                                                                                                     
                        "slug": "mackenzie-strachan",                                                                                                         
                        "shortName": "M. Strachan",                                                                                                           
                        "position": "M",                                                                                                                      
                        "jerseyNumber": "4",                                                                                                                  
                        "height": null,                                                                                                                       
                        "userCount": 3,                                                                                                                       
                        "sofascoreId": null,                                                                                                                  
                        "country": null,                                                                                                                      
                        "marketValueCurrency": "EUR",                                                                                                         
                        "dateOfBirthTimestamp": 1077494400,                                                                                                   
                        "proposedMarketValueRaw": null                                                                                                        
                  },                                                                                                                                          
                  "id": 124260152,                                                                                                                            
                  "time": 86,                                                                                                                                 
                  "addedTime": null,                                                                                                                          
                  "injury": false,                                                                                                                            
                  "isHome": false,                                                                                                                            
                  "incidentClass": "regular",                                                                                                                 
                  "reversedPeriodTime": 5                                                                                                                     
            },   
"""
