# ===================================================================
# UK FOOTBALL DATA PIPELINE CONFIGURATION
# ===================================================================
# This file defines the scope of data to be processed.
# Add or remove tournament/season IDs here to control the pipeline.

process_settings:
  # Seasons that are currently in-progress and require scraping and updates.
  # These are the season IDs for the 25/26 season.
  live_seasons:
    - 76986 # England - Premier League
    - 77347 # England - Championship
    - 77352 # England - League One
    - 77351 # England - League Two
    - 77128 # Scotland - Premiership
    - 77037 # Scotland - Championship

  # The final destination for the processed CSV files.
  output_directory: "uk_football_data_20_26"


data_scope:
  england:
    # Premier League
    1:
      - 29415 # 20/21
      - 37036 # 21/22
      - 41886 # 22/23
      - 52186 # 23/24
      - 61627 # 24/25
      - 76986 # 25/26
    # Championship
    2:
      - 29438 # 20/21
      - 37154 # 21/22
      - 42401 # 22/23
      - 52367 # 23/24
      - 61961 # 24/25
      - 77347 # 25/26
    # League One
    3:
      - 29439 # 20/21
      - 37155 # 21/22
      - 42402 # 22/23
      - 52370 # 23/24
      - 61959 # 24/25
      - 77352 # 25/26
    # League Two
    84:
      - 29441 # 20/21
      - 37156 # 21/22
      - 42403 # 22/23
      - 52368 # 23/24
      - 61960 # 24/25
      - 77351 # 25/26

  scotland:
    # Premiership
    54:
      - 28212 # 20/21
      - 37029 # 21/22
      - 41957 # 22/23
      - 52588 # 23/24
      - 62408 # 24/25
      - 77128 # 25/26
    # Championship
    55:
      - 29268 # 20/21
      - 37030 # 21/22
      - 41958 # 22/23
      - 52606 # 23/24
      - 62411 # 24/25
      - 77037 # 25/26
