# Quality assessment configuration
quality:
  # Which components to process (can disable some for testing)
  active_components: ["base" , "stats", "lineup", "incidents"]
  # active_components: ["base", "stats", "lineup", "incidents", "graph"]
#    - "base"
#    - "stats" 
#    - "lineup"
#    - "incidents"
#    - "graph"
  # Hash normalization (fields to ignore when hashing)
  comparator_exclusions:
    common: []
    base: []
    stats: []
    lineup: []
    incidents: []
    graph: []

  # Retry configuration
  retry:
    max_attempts: 2
    delay_seconds: 30.0
    

# Storage paths
storage:
  base_dir: "data"
  runs_subdir: "runs"
  analysis_subdir: "analysis" 
  golden_subdir: "golden"
  logs_subdir: "logs"

  save_file_formats:
    run_full: "{number}_full_{date}.pkl"
    run_part: "{number}_part_{date}.pkl"
    consensus: "consensus_{number}_{date}.pkl"

  file_formats:
    tournament: "tournament_{tournament_id}"
    season: "season_{season_id}"
